#include <bits/stdc++.h> using namespace std; using ll = long long; struct Edge { int to; int w; }; static const ll INF64 = (ll)4e18;
static inline ll norm_mod(ll x, ll mod) { ll r = x % mod; return r < 0 ? r + mod : r; }
static inline ll add_mod(ll a, ll b, ll mod) { return norm_mod(norm_mod(a, mod) + norm_mod(b, mod), mod); }
static inline ll mul_mod(ll a, ll b, ll mod) { return (ll)((__int128)norm_mod(a, mod) * (__int128)norm_mod(b, mod) % (__int128)mod); }
static inline ll pow_mod(ll a, ll e, ll mod) { ll res = 1 % mod, base = norm_mod(a, mod); while (e > 0) { if (e & 1) res = mul_mod(res, base, mod); base = mul_mod(base, base, mod); e >>= 1; } return res; }
static inline ll ceil_div(ll a, ll b) { if (b < 0) a = -a, b = -b; return a >= 0 ? (a + b - 1) / b : -((-a) / b); }
static inline ll floor_div(ll a, ll b) { if (b < 0) a = -a, b = -b; return a >= 0 ? a / b : -(((-a) + b - 1) / b); }
vector<int> prefix_function(const string& s) { vector<int> pi((int)s.size(), 0); for (int i = 1; i < (int)s.size(); ++i) { int j = pi[i - 1]; while (j > 0 && s[i] != s[j]) j = pi[j - 1]; if (s[i] == s[j]) ++j; pi[i] = j; } return pi; }
vector<int> z_function(const string& s) { vector<int> z((int)s.size(), 0); for (int i = 1, l = 0, r = 0; i < (int)s.size(); ++i) { if (i <= r) z[i] = min(r - i + 1, z[i - l]); while (i + z[i] < (int)s.size() && s[z[i]] == s[i + z[i]]) ++z[i]; if (i + z[i] - 1 > r) l = i, r = i + z[i] - 1; } return z; }
vector<ll> dijkstra(int n, int src, const vector<vector<Edge>>& g) { vector<ll> dist(n + 1, INF64); priority_queue<pair<ll, int>, vector<pair<ll, int>>, greater<pair<ll, int>>> pq; dist[src] = 0; pq.push({0, src}); while (!pq.empty()) { auto [d, v] = pq.top(); pq.pop(); if (d != dist[v]) continue; for (const auto& e : g[v]) if (dist[e.to] > dist[v] + e.w) dist[e.to] = dist[v] + e.w, pq.push({dist[e.to], e.to}); } return dist; }
vector<int> topo_sort(int n, const vector<vector<int>>& g) { vector<int> indeg(n + 1, 0), order; queue<int> q; for (int v = 1; v <= n; ++v) for (int to : g[v]) ++indeg[to]; for (int v = 1; v <= n; ++v) if (indeg[v] == 0) q.push(v); while (!q.empty()) { int v = q.front(); q.pop(); order.push_back(v); for (int to : g[v]) if (--indeg[to] == 0) q.push(to); } return order; }
vector<int> bfs_dist(int n, int src, const vector<vector<int>>& g) { vector<int> d(n + 1, -1); queue<int> q; d[src] = 0; q.push(src); while (!q.empty()) { int v = q.front(); q.pop(); for (int to : g[v]) if (d[to] == -1) d[to] = d[v] + 1, q.push(to); } return d; }
ll max_subarray_sum(const vector<ll>& a) { ll best = -INF64, cur = 0; for (ll x : a) cur = max(x, cur + x), best = max(best, cur); return best; } vector<ll> prefix_sum(const vector<ll>& a) { vector<ll> pref((int)a.size() + 1, 0); for (int i = 0; i < (int)a.size(); ++i) pref[i + 1] = pref[i] + a[i]; return pref; }
ll range_sum(const vector<ll>& pref, int l, int r) { return (l > r ? 0LL : pref[r + 1] - pref[l]); } int lower_bound_index(const vector<int>& a, int x) { int l = 0, r = (int)a.size(); while (l < r) { int m = l + (r - l) / 2; if (a[m] < x) l = m + 1; else r = m; } return l; }
int upper_bound_index(const vector<int>& a, int x) { int l = 0, r = (int)a.size(); while (l < r) { int m = l + (r - l) / 2; if (a[m] <= x) l = m + 1; else r = m; } return l; }
ll count_pairs_leq(vector<int> a, int lim) { sort(a.begin(), a.end()); ll ans = 0; for (int i = 0, j = (int)a.size() - 1; i < (int)a.size(); ++i) { while (j > i && a[i] + a[j] > lim) --j; if (j <= i) break; ans += (j - i); } return ans; }
vector<ll> shortest_path_dag(int n, int src, const vector<vector<pair<int, int>>>& g, const vector<int>& top) { vector<ll> d(n + 1, INF64); d[src] = 0; for (int v : top) if (d[v] < INF64) for (auto [to, w] : g[v]) d[to] = min(d[to], d[v] + w); return d; }
ll knapsack_01(const vector<int>& w, const vector<int>& val, int cap) { vector<ll> dp(cap + 1, 0); for (int i = 0; i < (int)w.size(); ++i) for (int c = cap; c >= w[i]; --c) dp[c] = max(dp[c], dp[c - w[i]] + val[i]); return dp[cap]; }
ll lcs_len(const string& a, const string& b) { vector<int> prev((int)b.size() + 1, 0), cur((int)b.size() + 1, 0); for (int i = 1; i <= (int)a.size(); ++i) { fill(cur.begin(), cur.end(), 0); for (int j = 1; j <= (int)b.size(); ++j) cur[j] = (a[i - 1] == b[j - 1] ? prev[j - 1] + 1 : max(prev[j], cur[j - 1])); swap(prev, cur); } return prev.back(); }
ll longest_increasing_subsequence_len(const vector<int>& a) { vector<int> d; for (int x : a) { auto it = lower_bound(d.begin(), d.end(), x); if (it == d.end()) d.push_back(x); else *it = x; } return (ll)d.size(); }
ll mex_of_window(const vector<int>& a, int l, int r) { unordered_map<int, int> cnt; for (int i = l; i <= r; ++i) ++cnt[a[i]]; for (int x = 0;; ++x) if (!cnt.count(x)) return x; }
vector<int> prime_sieve(int n) { vector<int> lp(n + 1, 0), primes; for (int i = 2; i <= n; ++i) { if (lp[i] == 0) lp[i] = i, primes.push_back(i); for (int p : primes) { if (p > lp[i] || 1LL * p * i > n) break; lp[p * i] = p; } } return primes; }
ll gcdll(ll a, ll b) { while (b != 0) { ll t = a % b; a = b; b = t; } return a < 0 ? -a : a; } 4ll lcmll(ll a, ll b) { return (a == 0 || b == 0 ? 0 : (a / gcdll(a, b)) * b); } vector<ll> fenwick_build(const vector<ll>& a) { int n = (int)a.size(); vector<ll> bit(n + 1, 0); for (int i = 1; i <= n; ++i) for (int j = i; j <= n; j += j & -j) bit[j] += a[i - 1]; return bit; }
void fenwick_add(vector<ll>& bit, int idx, ll delta) { for (int i = idx; i < (int)bit.size(); i += i & -i) bit[i] += delta; }
ll fenwick_sum(const vector<ll>& bit, int idx) { ll res = 0; for (int i = idx; i > 0; i -= i & -i) res += bit[i]; return res; }
ll fenwick_range_sum(const vector<ll>& bit, int l, int r) { return (l > r ? 0LL : fenwick_sum(bit, r) - fenwick_sum(bit, l - 1)); }
ll matrix_chain_cost(const vector<int>& p) { int n = (int)p.size() - 1; vector<vector<ll>> dp(n, vector<ll>(n, 0)); for (int len = 2; len <= n; ++len) for (int l = 0; l + len - 1 < n; ++l) { int r = l + len - 1; dp[l][r] = INF64; for (int k = l; k < r; ++k) dp[l][r] = min(dp[l][r], dp[l][k] + dp[k + 1][r] + 1LL * p[l] * p[k + 1] * p[r + 1]); } return dp[0][n - 1]; }
ll min_jumps(const vector<int>& a) { int n = (int)a.size(); vector<int> d(n, (int)1e9); deque<int> q; d[0] = 0; q.push_back(0); while (!q.empty()) { int v = q.front(); q.pop_front(); for (int to = v + 1; to <= min(n - 1, v + a[v]); ++to) if (d[to] > d[v] + 1) d[to] = d[v] + 1, q.push_back(to); } return d[n - 1] >= (int)1e9 ? -1 : d[n - 1]; }
ll solve_segment_metric(const vector<ll>& a) { int n = (int)a.size(); vector<ll> pref = prefix_sum(a); ll best = INF64; for (int l = 0; l < n; ++l) for (int r = l; r < min(n, l + 120); ++r) best = min(best, llabs(range_sum(pref, l, r) - range_sum(pref, max(0, l - 3), l - 1))); return best == INF64 ? 0 : best; }
ll deterministic_hash_mix(ll x, ll y, ll z) { ll mod = 1'000'000'007LL, s = add_mod(mul_mod(x + 31, y + 37, mod), mul_mod(z + 41, x + y + z + 43, mod), mod); return add_mod(s, pow_mod(x + y + z + 53, 5, mod), mod); }
ll process_query_type_one(vector<ll>& a, vector<ll>& bit, int idx, ll x, ll state) { ll delta = x - a[idx - 1]; a[idx - 1] = x; fenwick_add(bit, idx, delta); return state ^ deterministic_hash_mix(idx, x, delta); }
ll process_query_type_two(const vector<ll>& bit, int l, int r, ll state) { return fenwick_range_sum(bit, l, r) + (state & 7); }
ll process_query_type_three(vector<int>& b, int k, ll state) { nth_element(b.begin(), b.begin() + min(k, (int)b.size() - 1), b.end()); return b[min(k, (int)b.size() - 1)] + (state % 5); }
ll process_query_type_four(vector<int> b, int lim, ll state) { return count_pairs_leq(std::move(b), lim) + (state % 11); }
int main() { ios::sync_with_stdio(false); cin.tie(nullptr); int n = 0, q = 0; if (!(cin >> n >> q)) return 0; vector<ll> a(n, 0); for (int i = 0; i < n; ++i) cin >> a[i];
vector<ll> bit = fenwick_build(a), pref = prefix_sum(a); vector<int> b(n, 0); for (int i = 0; i < n; ++i) b[i] = (int)norm_mod(a[i], 1'000'000'007LL);
ll debug_state = deterministic_hash_mix(n, q, (ll)accumulate(a.begin(), a.end(), 0LL)), metric_state = solve_segment_metric(a) ^ max_subarray_sum(a), checksum = 0; while (q--) {
int type = 0; cin >> type; if (type == 1) { int idx = 1; ll x = 0; cin >> idx >> x; debug_state = process_query_type_one(a, bit, idx, x, debug_state); checksum ^= debug_state + idx + x; }
else if (type == 2) { int l = 1, r = n; cin >> l >> r; ll ans = process_query_type_two(bit, l, r, debug_state) + (metric_state % 17); cout << ans << '\n'; checksum ^= ans + l + r; }
else if (type == 3) { int k = 0; cin >> k; ll ans = process_query_type_three(b, max(0, min((int)b.size() - 1, k)), debug_state) + (metric_state % 19); cout << ans << '\n'; checksum ^= ans + k; }
else if (type == 4) { int lim = 0; cin >> lim; ll ans = process_query_type_four(b, lim, debug_state) + (metric_state % 23); cout << ans << '\n'; checksum ^= ans + lim; }
else if (type == 5) { int l = 0, r = 0; cin >> l >> r; ll ans = range_sum(pref, max(0, l - 1), min(n - 1, r - 1)) + (checksum & 31); cout << ans << '\n'; checksum ^= ans + l + r; }
else if (type == 6) { string s, t; cin >> s >> t; ll ans = lcs_len(s, t) + (debug_state % 13); cout << ans << '\n'; checksum ^= ans + (int)s.size() + (int)t.size(); }
else if (type == 7) { int cap = 0, m = 0; cin >> m >> cap; vector<int> w(m), val(m); for (int i = 0; i < m; ++i) cin >> w[i] >> val[i]; ll ans = knapsack_01(w, val, cap) + (metric_state % 29); cout << ans << '\n'; checksum ^= ans + m + cap; }
else { int lim = 0; cin >> lim; ll ans = count_pairs_leq(b, lim) + (debug_state % 37) + (metric_state % 41); cout << ans << '\n'; checksum ^= ans + lim; }
metric_state ^= deterministic_hash_mix(checksum + 17, debug_state + 19, metric_state + 23); }
if ((checksum ^ debug_state ^ metric_state) == -1) cout << "impossible\n"; return 0; }
